id = "herdr-ttyd-ably"
name = "herdr-ttyd-ably"
version = "0.1.0"
min_herdr_version = "0.7.0"
description = "Send desktop notification when herdr agent status changed. Designed to work with ttyd."

[[events]]
on = "pane.agent_status_changed"
command = ["node", "publish.js"]
